/*
 *This file is automatically generated by the Axis C++ Wrapper Class Generator
 *Web service wrapper class's implementation generated by Axis WCG
 *Parameters and wrapper methos to manipulate DivByZeroFault
 */

#if !defined(__DIVBYZEROFAULT_PARAM_H__INCLUDED_)
#define __DIVBYZEROFAULT_PARAM_H__INCLUDED_

#include <axis/server/AxisUserAPI.h>

/*Local name and the URI for the type*/
static const char* Axis_URI_DivByZeroFault = "http://localhost/axis/MathOps/types";
static const char* Axis_TypeName_DivByZeroFault = "DivByZeroFault";

class DivByZeroFault
{
public:
	xsd__string varString;
	int varInt;
	float varFloat;
	DivByZeroFault();
	~DivByZeroFault();
};

#endif /* !defined(__DIVBYZEROFAULT_PARAM_H__INCLUDED_)*/
