// Copyright 2003-2004 The Apache Software Foundation.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//		This file is automatically generated by the Axis C++ Wrapper Class Generator
//		Service file containing the two export functions of the Web service Library

#include "InteropTestPortTypeWrapper.h" 

extern "C" {
STORAGE_CLASS_INFO
int GetClassInstance(BasicHandler **inst)
{
	*inst = new BasicHandler();
	InteropTestPortTypeWrapper* pService = new InteropTestPortTypeWrapper();
	(*inst)->_functions = 0;
	if (pService)
	{
		(*inst)->_object = pService;
		return pService->init();
	}
	return AXIS_FAIL;
}

STORAGE_CLASS_INFO 
int DestroyInstance(BasicHandler *inst)
{
	if (inst)
	{
		WrapperClassHandler* pWCH = static_cast<WrapperClassHandler*>(inst->_object);
		pWCH->fini();
		delete pWCH;
		delete inst;
		return AXIS_SUCCESS;
	}
	return AXIS_FAIL;
}
}

