///////////////////////////////////////////////////////////////////////////////////
//This file is automatically generated by the Axis C++ Wrapper Class Generator
//Web service wrapper class's implementation generated by Axis WCG
//Parameters and wrapper methos to manipulate SOAPStruct
////////////////////////////////////////////////////////////////////////////////////

#if !defined(__SOAPSTRUCT_PARAM_H__OF_AXIS_INCLUDED_)
#define __SOAPSTRUCT_PARAM_H__OF_AXIS_INCLUDED_

#include <axis/AxisUserAPI.hpp>

AXIS_CPP_NAMESPACE_USE

//Local name and the URI for the type
static const char* Axis_URI_SOAPStruct = "http://soapinterop.org/xsd";
static const char* Axis_TypeName_SOAPStruct = "SOAPStruct";

class SOAPStruct
{
public:
	AxisChar* varString;
	int varInt;
	float varFloat;
	~SOAPStruct();
	SOAPStruct();
};

#endif // !defined(__SOAPSTRUCT_PARAM_H__OF_AXIS_INCLUDED_)
