/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub Class for remote web service 
 */

#if !defined(__EXTENSIBILITYQUERYPORTTYPE_CLIENTSTUB_H__INCLUDED_)
#define __EXTENSIBILITYQUERYPORTTYPE_CLIENTSTUB_H__INCLUDED_

#include <axis/client/Stub.hpp>
#include "ExtensibilityType.h"
#include "AxisClientException.h"


class ExtensibilityQueryPortType  :public Stub
{
public:
	ExtensibilityQueryPortType(const char* pchEndpointUri, AXIS_PROTOCOL_TYPE eProtocol=APTHTTP);
	ExtensibilityQueryPortType();
public:
	virtual ~ExtensibilityQueryPortType();
public: 
	AnyType* query(AnyType* Value0);
};

#endif /* !defined(__EXTENSIBILITYQUERYPORTTYPE_CLIENTSTUB_H__INCLUDED_)*/
