<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AxisAdminService" 
    targetNamespace="http://www.opensource.lk/AxisAdmin" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:tns="http://www.opensource.lk/AxisAdmin" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsd1="http://www.opensource.lk/xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <types>
        <schema targetNamespace="http://www.opensource.lk/xsd"
            xmlns="http://www.w3.org/2001/XMLSchema" 
            xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <element name="updateWSDD">
                <complexType>
                    <sequence>
                        <element name="wsdd" type="xsd:base64Binary"/>
                    </sequence>
                </complexType>
            </element>
            <element name="updateWSDDResponse">
                <complexType>
                    <sequence>
                        <element name="return" type="xsd:boolean"/>
                    </sequence>
                </complexType>
            </element>
        </schema>
    </types>
    <message name="updateWSDD">
        <part element="xsd1:updateWSDD" name="parameters"/>
    </message>
    <message name="updateWSDDResponse">
        <part element="xsd1:updateWSDDResponse" name="parameters"/>
    </message>
    <portType name="AxisAdminService">
        <operation name="updateWSDD">
            <input message="tns:updateWSDD" name="updateWSDD"/>
            <output message="tns:updateWSDDResponse" name="updateWSDDResponse"/>
        </operation>
    </portType>
    <binding name="AxisAdminPortBinding" type="tns:AxisAdminService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="updateWSDD">
            <soap:operation soapAction="AxisAdmin#updateWSDD" style="document"/>
            <input name="updateWSDD">
                <soap:body namespace="http://www.opensource.lk/AxisAdmin" 
                    use="literal"/>
            </input>
            <output name="updateWSDDResponse">
                <soap:body namespace="http://www.opensource.lk/AxisAdmin" 
                    use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="AxisAdmin">
        <port binding="tns:AxisAdminPortBinding" 
            name="AxisAdminParamPort">
            <soap:address 
                location="http://localhost/axis/AxisAdmin"/>
        </port>
    </service>
</definitions>
