package org.soapinterop;
/*This class is automatically generated by 
*axis_lsf client stub generator
*The client side stub of the web service. 
*/

public class InteropTestPortTypeStub implements org.soapinterop.InteropTestPortType{

	private java.lang.String enduri;
	private javax.xml.namespace.QName SOAPAction;
	private org.apache.axismora.client.Service service;

	public InteropTestPortTypeStub(){
	}
	public InteropTestPortTypeStub(java.lang.String enduri){
		try{
			this.enduri = enduri;
			this.SOAPAction = new javax.xml.namespace.QName("InteropTestService");
			this.service = new org.apache.axismora.client.Service();
		}catch(Exception e){
			e.printStackTrace();
		}
	}

	public java.lang.String echoString(java.lang.String param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoString");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.StringParam op0 = new org.apache.axismora.wrappers.simpleType.StringParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","string"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","string"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.StringParam res = new org.apache.axismora.wrappers.simpleType.StringParam(mx);
		return res.getParam();
		}

	public java.lang.String[] echoStringArray(java.lang.String[] param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoStringArray");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		xsd.org.soapinterop.ArrayOfstring op0 = new xsd.org.soapinterop.ArrayOfstring();
		op0.setParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOfstring"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOfstring"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		xsd.org.soapinterop.ArrayOfstring res = (xsd.org.soapinterop.ArrayOfstring)(new xsd.org.soapinterop.ArrayOfstring()).desierialize(mx);
		 return (java.lang.String[])res.getParam();

		}

	public int echoInteger(int param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoInteger");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.IntParam op0 = new org.apache.axismora.wrappers.simpleType.IntParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","int"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","int"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.IntParam res = new org.apache.axismora.wrappers.simpleType.IntParam(mx);
		return res.getParam();
		}

	public int[] echoIntegerArray(int[] param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoIntegerArray");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		xsd.org.soapinterop.ArrayOfint op0 = new xsd.org.soapinterop.ArrayOfint();
		op0.setParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOfint"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOfint"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		xsd.org.soapinterop.ArrayOfint res = (xsd.org.soapinterop.ArrayOfint)(new xsd.org.soapinterop.ArrayOfint()).desierialize(mx);
		 return (int[])res.getParam();

		}

	public float echoFloat(float param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoFloat");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.FloatParam op0 = new org.apache.axismora.wrappers.simpleType.FloatParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","float"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","float"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.FloatParam res = new org.apache.axismora.wrappers.simpleType.FloatParam(mx);
		return res.getParam();
		}

	public float[] echoFloatArray(float[] param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoFloatArray");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		xsd.org.soapinterop.ArrayOffloat op0 = new xsd.org.soapinterop.ArrayOffloat();
		op0.setParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOffloat"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOffloat"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		xsd.org.soapinterop.ArrayOffloat res = (xsd.org.soapinterop.ArrayOffloat)(new xsd.org.soapinterop.ArrayOffloat()).desierialize(mx);
		 return (float[])res.getParam();

		}

	public xsd.org.soapinterop.SOAPStruct echoStruct(xsd.org.soapinterop.SOAPStruct param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoStruct");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","SOAPStruct"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","SOAPStruct"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		xsd.org.soapinterop.SOAPStruct res = (xsd.org.soapinterop.SOAPStruct)(new xsd.org.soapinterop.SOAPStruct()).desierialize(mx);
		 return res;

		}

	public xsd.org.soapinterop.SOAPStruct[] echoStructArray(xsd.org.soapinterop.SOAPStruct[] param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoStructArray");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		xsd.org.soapinterop.ArrayOfSOAPStruct op0 = new xsd.org.soapinterop.ArrayOfSOAPStruct();
		op0.setParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOfSOAPStruct"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOfSOAPStruct"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		xsd.org.soapinterop.ArrayOfSOAPStruct res = (xsd.org.soapinterop.ArrayOfSOAPStruct)(new xsd.org.soapinterop.ArrayOfSOAPStruct()).desierialize(mx);
		 return (xsd.org.soapinterop.SOAPStruct[])res.getParam();

		}

	public void echoVoid()throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoVoid");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.setTargetEndpointAddress(this.enduri);
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{});
		}

	public org.apache.axismora.wrappers.simpleType.Base64ByteArrayParam echoBase64(org.apache.axismora.wrappers.simpleType.Base64ByteArrayParam param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoBase64");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.Base64ByteArrayParam op0 = new org.apache.axismora.wrappers.simpleType.Base64ByteArrayParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","base64Binary"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","base64Binary"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.Base64ByteArrayParam res = new org.apache.axismora.wrappers.simpleType.Base64ByteArrayParam(mx);
		return res;
		}

	public org.apache.axismora.wrappers.simpleType.HexBinaryParam echoHexBinary(org.apache.axismora.wrappers.simpleType.HexBinaryParam param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoHexBinary");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.HexBinaryParam op0 = new org.apache.axismora.wrappers.simpleType.HexBinaryParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","hexBinary"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","hexBinary"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.HexBinaryParam res = new org.apache.axismora.wrappers.simpleType.HexBinaryParam(mx);
		return res;
		}

	public java.math.BigDecimal echoDecimal(java.math.BigDecimal param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoDecimal");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.BigDecimalParam op0 = new org.apache.axismora.wrappers.simpleType.BigDecimalParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","decimal"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","decimal"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.BigDecimalParam res = new org.apache.axismora.wrappers.simpleType.BigDecimalParam(mx);
		return res.getParam();
		}

	public boolean echoBoolean(boolean param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoBoolean");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.BooleanParam op0 = new org.apache.axismora.wrappers.simpleType.BooleanParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","boolean"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","boolean"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.BooleanParam res = new org.apache.axismora.wrappers.simpleType.BooleanParam(mx);
		return res.getParam();
		}

	public int echoStructAsSimpleTypes(xsd.org.soapinterop.SOAPStruct param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoStructAsSimpleTypes");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","SOAPStruct"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","int"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		org.apache.axismora.wrappers.simpleType.IntParam res = new org.apache.axismora.wrappers.simpleType.IntParam(mx);
		return res.getParam();
		}

	public xsd.org.soapinterop.SOAPStruct echoSimpleTypesAsStruct(java.lang.String param0,int param1,float param2)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoSimpleTypesAsStruct");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.StringParam op0 = new org.apache.axismora.wrappers.simpleType.StringParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","string"),javax.xml.rpc.ParameterMode.IN);
		org.apache.axismora.wrappers.simpleType.IntParam op1 = new org.apache.axismora.wrappers.simpleType.IntParam(param1);
		call.addParameter("param1",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","int"),javax.xml.rpc.ParameterMode.IN);
		org.apache.axismora.wrappers.simpleType.FloatParam op2 = new org.apache.axismora.wrappers.simpleType.FloatParam(param2);
		call.addParameter("param2",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","float"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","SOAPStruct"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0,op1,op2});
		xsd.org.soapinterop.SOAPStruct res = (xsd.org.soapinterop.SOAPStruct)(new xsd.org.soapinterop.SOAPStruct()).desierialize(mx);
		 return res;

		}

	public java.lang.String[] echo2DStringArray(java.lang.String[] param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echo2DStringArray");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		xsd.org.soapinterop.ArrayOfString2D op0 = new xsd.org.soapinterop.ArrayOfString2D();
		op0.setParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOfString2D"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","ArrayOfString2D"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		xsd.org.soapinterop.ArrayOfString2D res = (xsd.org.soapinterop.ArrayOfString2D)(new xsd.org.soapinterop.ArrayOfString2D()).desierialize(mx);
		 return (java.lang.String[])res.getParam();

		}

	public xsd.org.soapinterop.SOAPStructStruct echoNestedStruct(xsd.org.soapinterop.SOAPStructStruct param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoNestedStruct");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","SOAPStructStruct"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","SOAPStructStruct"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		xsd.org.soapinterop.SOAPStructStruct res = (xsd.org.soapinterop.SOAPStructStruct)(new xsd.org.soapinterop.SOAPStructStruct()).desierialize(mx);
		 return res;

		}

	public xsd.org.soapinterop.SOAPArrayStruct echoNestedArray(xsd.org.soapinterop.SOAPArrayStruct param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoNestedArray");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soapinterop.org/xsd","SOAPArrayStruct"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soapinterop.org/xsd","SOAPArrayStruct"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		xsd.org.soapinterop.SOAPArrayStruct res = (xsd.org.soapinterop.SOAPArrayStruct)(new xsd.org.soapinterop.SOAPArrayStruct()).desierialize(mx);
		 return res;

		}

	public java.lang.String echoToken(java.lang.String param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoToken");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.StringParam op0 = new org.apache.axismora.wrappers.simpleType.StringParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","token"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","token"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.StringParam res = new org.apache.axismora.wrappers.simpleType.StringParam(mx);
		return res.getParam();
		}

	public java.lang.String echoNormalizedString(java.lang.String param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoNormalizedString");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.StringParam op0 = new org.apache.axismora.wrappers.simpleType.StringParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","normalizedString"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","normalizedString"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.StringParam res = new org.apache.axismora.wrappers.simpleType.StringParam(mx);
		return res.getParam();
		}

	public long echoUnsignedLong(long param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoUnsignedLong");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.LongParam op0 = new org.apache.axismora.wrappers.simpleType.LongParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","unsignedLong"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","unsignedLong"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.LongParam res = new org.apache.axismora.wrappers.simpleType.LongParam(mx);
		return res.getParam();
		}

	public int echoUnsignedInt(int param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoUnsignedInt");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.IntParam op0 = new org.apache.axismora.wrappers.simpleType.IntParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","unsignedInt"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","unsignedInt"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.IntParam res = new org.apache.axismora.wrappers.simpleType.IntParam(mx);
		return res.getParam();
		}

	public short echoUnsignedShort(short param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoUnsignedShort");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.ShortParam op0 = new org.apache.axismora.wrappers.simpleType.ShortParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","unsignedShort"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","unsignedShort"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.ShortParam res = new org.apache.axismora.wrappers.simpleType.ShortParam(mx);
		return res.getParam();
		}

	public byte echoUnsignedByte(byte param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoUnsignedByte");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.ByteParam op0 = new org.apache.axismora.wrappers.simpleType.ByteParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","unsignedByte"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","unsignedByte"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.ByteParam res = new org.apache.axismora.wrappers.simpleType.ByteParam(mx);
		return res.getParam();
		}

	public int echoNonNegativeInteger(int param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoNonNegativeInteger");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.IntParam op0 = new org.apache.axismora.wrappers.simpleType.IntParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","nonNegativeInteger"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","nonNegativeInteger"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.IntParam res = new org.apache.axismora.wrappers.simpleType.IntParam(mx);
		return res.getParam();
		}

	public int echoPositiveInteger(int param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoPositiveInteger");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.IntParam op0 = new org.apache.axismora.wrappers.simpleType.IntParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","positiveInteger"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","positiveInteger"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.IntParam res = new org.apache.axismora.wrappers.simpleType.IntParam(mx);
		return res.getParam();
		}

	public int echoNonPositiveInteger(int param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoNonPositiveInteger");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.IntParam op0 = new org.apache.axismora.wrappers.simpleType.IntParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","nonPositiveInteger"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","nonPositiveInteger"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.IntParam res = new org.apache.axismora.wrappers.simpleType.IntParam(mx);
		return res.getParam();
		}

	public int echoNegativeInteger(int param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("echoNegativeInteger");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		org.apache.axismora.wrappers.simpleType.IntParam op0 = new org.apache.axismora.wrappers.simpleType.IntParam(param0);
		call.addParameter("param0",new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","negativeInteger"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema","negativeInteger"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{op0});
		org.apache.axismora.wrappers.simpleType.IntParam res = new org.apache.axismora.wrappers.simpleType.IntParam(mx);
		return res.getParam();
		}
}
