package org.soapinterop;
/*This class is automatically generated by 
*axis_lsf client service generator
*The client side Locator of the web service. 
*/

public class InteropTestPortTypeLocator  {

	private org.soapinterop.InteropTestPortType ws;
	public InteropTestPortTypeLocator(){
	}
	public InteropTestPortTypeLocator(java.lang.String enduri){
	this.ws = new org.soapinterop.InteropTestPortTypeStub(enduri);
	}

	public org.soapinterop.InteropTestPortType getStub(){
		return this.ws;
	}
}
