package org.soapinterop;
/*This interface is automatically generated by 
*Axisj_lsf client service generator
*The client side representation of the web service. 
*/

public interface InteropTestPortType extends java.rmi.Remote {
	public java.lang.String echoString(java.lang.String param0)throws java.rmi.RemoteException;
	public java.lang.String[] echoStringArray(java.lang.String[] param0)throws java.rmi.RemoteException;
	public int echoInteger(int param0)throws java.rmi.RemoteException;
	public int[] echoIntegerArray(int[] param0)throws java.rmi.RemoteException;
	public float echoFloat(float param0)throws java.rmi.RemoteException;
	public float[] echoFloatArray(float[] param0)throws java.rmi.RemoteException;
	public xsd.org.soapinterop.SOAPStruct echoStruct(xsd.org.soapinterop.SOAPStruct param0)throws java.rmi.RemoteException;
	public xsd.org.soapinterop.SOAPStruct[] echoStructArray(xsd.org.soapinterop.SOAPStruct[] param0)throws java.rmi.RemoteException;
	public void echoVoid()throws java.rmi.RemoteException;
	public org.apache.axismora.wrappers.simpleType.Base64ByteArrayParam echoBase64(org.apache.axismora.wrappers.simpleType.Base64ByteArrayParam param0)throws java.rmi.RemoteException;
	public org.apache.axismora.wrappers.simpleType.HexBinaryParam echoHexBinary(org.apache.axismora.wrappers.simpleType.HexBinaryParam param0)throws java.rmi.RemoteException;
	public java.math.BigDecimal echoDecimal(java.math.BigDecimal param0)throws java.rmi.RemoteException;
	public boolean echoBoolean(boolean param0)throws java.rmi.RemoteException;
	public int echoStructAsSimpleTypes(xsd.org.soapinterop.SOAPStruct param0)throws java.rmi.RemoteException;
	public xsd.org.soapinterop.SOAPStruct echoSimpleTypesAsStruct(java.lang.String param0,int param1,float param2)throws java.rmi.RemoteException;
	public java.lang.String[] echo2DStringArray(java.lang.String[] param0)throws java.rmi.RemoteException;
	public xsd.org.soapinterop.SOAPStructStruct echoNestedStruct(xsd.org.soapinterop.SOAPStructStruct param0)throws java.rmi.RemoteException;
	public xsd.org.soapinterop.SOAPArrayStruct echoNestedArray(xsd.org.soapinterop.SOAPArrayStruct param0)throws java.rmi.RemoteException;
	public java.lang.String echoToken(java.lang.String param0)throws java.rmi.RemoteException;
	public java.lang.String echoNormalizedString(java.lang.String param0)throws java.rmi.RemoteException;
	public long echoUnsignedLong(long param0)throws java.rmi.RemoteException;
	public int echoUnsignedInt(int param0)throws java.rmi.RemoteException;
	public short echoUnsignedShort(short param0)throws java.rmi.RemoteException;
	public byte echoUnsignedByte(byte param0)throws java.rmi.RemoteException;
	public int echoNonNegativeInteger(int param0)throws java.rmi.RemoteException;
	public int echoPositiveInteger(int param0)throws java.rmi.RemoteException;
	public int echoNonPositiveInteger(int param0)throws java.rmi.RemoteException;
	public int echoNegativeInteger(int param0)throws java.rmi.RemoteException;
}
