/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub implementation for remote web service.
 */

#include "InteropTestPortTypeB.h"

extern int Axis_DeSerialize_SOAPArrayStruct(SOAPArrayStruct* param, IWrapperSoapDeSerializer* pDZ);
extern void* Axis_Create_SOAPArrayStruct(SOAPArrayStruct *Obj, bool bArray, int nSize);
extern void Axis_Delete_SOAPArrayStruct(SOAPArrayStruct* param, bool bArray, int nSize);
extern int Axis_Serialize_SOAPArrayStruct(SOAPArrayStruct* param, IWrapperSoapSerializer* pSZ, bool bArray);
extern int Axis_GetSize_SOAPArrayStruct();

extern int Axis_DeSerialize_SOAPStruct(SOAPStruct* param, IWrapperSoapDeSerializer* pDZ);
extern void* Axis_Create_SOAPStruct(SOAPStruct *Obj, bool bArray, int nSize);
extern void Axis_Delete_SOAPStruct(SOAPStruct* param, bool bArray, int nSize);
extern int Axis_Serialize_SOAPStruct(SOAPStruct* param, IWrapperSoapSerializer* pSZ, bool bArray);
extern int Axis_GetSize_SOAPStruct();

extern int Axis_DeSerialize_SOAPStructStruct(SOAPStructStruct* param, IWrapperSoapDeSerializer* pDZ);
extern void* Axis_Create_SOAPStructStruct(SOAPStructStruct *Obj, bool bArray, int nSize);
extern void Axis_Delete_SOAPStructStruct(SOAPStructStruct* param, bool bArray, int nSize);
extern int Axis_Serialize_SOAPStructStruct(SOAPStructStruct* param, IWrapperSoapSerializer* pSZ, bool bArray);
extern int Axis_GetSize_SOAPStructStruct();

void* get_InteropTestPortTypeB_stub(const char* pchEndPointUri)
{	if(pchEndPointUri)
	{
		return getStubObject(APTHTTP1_1, pchEndPointUri);
	}
	else
	{
		return getStubObject(APTHTTP1_1, "http://localhost/axis/cgroupB");
	}
}
void destroy_InteropTestPortTypeB_stub(void* p){
	destroyStubObject(p);
}
int get_InteropTestPortTypeB_Status(void* pStub){
	Call* pCall = (Call*)pStub;
	if ( pStub == NULL ) return AXIS_SUCCESS; else return pCall->_functions->getStatus(pCall->_object);
	}

/*Methods corresponding to the web service methods*/

/*
 * This method wrap the service methodechoStructAsSimpleTypes
 */
void echoStructAsSimpleTypes(void* pStub, SOAPStruct* Value0, AXIS_OUT_PARAM  xsd__string *OutValue0, AXIS_OUT_PARAM  int *OutValue1, AXIS_OUT_PARAM  float *OutValue2)
{
	Call* pCall = (Call*)pStub;
	/* Following will establish the connections with the server too */
	if (AXIS_SUCCESS != pCall->_functions->initialize(pCall->_object,C_RPC_PROVIDER, NORMAL_CHANNEL)) return ;
	pCall->_functions->setTransportProperty(pCall->_object,SOAPACTION_HEADER , "cgroupB#echoStructAsSimpleTypes");
	pCall->_functions->setSOAPVersion(pCall->_object, SOAP_VER_1_1);
	pCall->_functions->setOperation(pCall->_object, "echoStructAsSimpleTypes", "http://soapinterop.org/");
	pCall->_functions->addCmplxParameter(pCall->_object, Value0, (void*)Axis_Serialize_SOAPStruct, (void*)Axis_Delete_SOAPStruct, "inputStruct", 0);
	if (AXIS_SUCCESS == pCall->_functions->invoke(pCall->_object))
	{
		if(AXIS_SUCCESS == pCall->_functions->checkMessage(pCall->_object, "echoStructAsSimpleTypesResponse", ""))
		{
			*OutValue0 = pCall->_functions->getElementAsString(pCall->_object, "outputString", 0);
			*OutValue1 = pCall->_functions->getElementAsInt(pCall->_object, "outputInteger", 0);
			*OutValue2 = pCall->_functions->getElementAsFloat(pCall->_object, "outputFloat", 0);
		}
	}
	pCall->_functions->unInitialize(pCall->_object);
}


/*
 * This method wrap the service methodechoSimpleTypesAsStruct
 */
SOAPStruct* echoSimpleTypesAsStruct(void* pStub, xsd__string Value0, int Value1, float Value2)
{
	Call* pCall = (Call*)pStub;
	SOAPStruct* pReturn = NULL;
	/* Following will establish the connections with the server too */
	if (AXIS_SUCCESS != pCall->_functions->initialize(pCall->_object,C_RPC_PROVIDER, NORMAL_CHANNEL)) return pReturn;
	pCall->_functions->setTransportProperty(pCall->_object,SOAPACTION_HEADER , "cgroupB#echoSimpleTypesAsStruct");
	pCall->_functions->setSOAPVersion(pCall->_object, SOAP_VER_1_1);
	pCall->_functions->setOperation(pCall->_object, "echoSimpleTypesAsStruct", "http://soapinterop.org/");
	pCall->_functions->addParameter(pCall->_object, (void*)&Value0, "inputString", XSD_STRING);
	pCall->_functions->addParameter(pCall->_object, (void*)&Value1, "inputInteger", XSD_INT);
	pCall->_functions->addParameter(pCall->_object, (void*)&Value2, "inputFloat", XSD_FLOAT);
	if (AXIS_SUCCESS == pCall->_functions->invoke(pCall->_object))
	{
		if(AXIS_SUCCESS == pCall->_functions->checkMessage(pCall->_object, "echoSimpleTypesAsStructResponse", ""))
		{
			pReturn = (SOAPStruct*)pCall->_functions->getCmplxObject(pCall->_object, (void*) Axis_DeSerialize_SOAPStruct, (void*) Axis_Create_SOAPStruct, (void*) Axis_Delete_SOAPStruct,"return", 0);
		}
	}
	pCall->_functions->unInitialize(pCall->_object);
	return pReturn;
}


/*
 * This method wrap the service methodechoNestedStruct
 */
SOAPStructStruct* echoNestedStruct(void* pStub, SOAPStructStruct* Value0)
{
	Call* pCall = (Call*)pStub;
	SOAPStructStruct* pReturn = NULL;
	/* Following will establish the connections with the server too */
	if (AXIS_SUCCESS != pCall->_functions->initialize(pCall->_object,C_RPC_PROVIDER, NORMAL_CHANNEL)) return pReturn;
	pCall->_functions->setTransportProperty(pCall->_object,SOAPACTION_HEADER , "cgroupB#echoNestedStruct");
	pCall->_functions->setSOAPVersion(pCall->_object, SOAP_VER_1_1);
	pCall->_functions->setOperation(pCall->_object, "echoNestedStruct", "http://soapinterop.org/");
	pCall->_functions->addCmplxParameter(pCall->_object, Value0, (void*)Axis_Serialize_SOAPStructStruct, (void*)Axis_Delete_SOAPStructStruct, "inputStruct", 0);
	if (AXIS_SUCCESS == pCall->_functions->invoke(pCall->_object))
	{
		if(AXIS_SUCCESS == pCall->_functions->checkMessage(pCall->_object, "echoNestedStructResponse", ""))
		{
			pReturn = (SOAPStructStruct*)pCall->_functions->getCmplxObject(pCall->_object, (void*) Axis_DeSerialize_SOAPStructStruct, (void*) Axis_Create_SOAPStructStruct, (void*) Axis_Delete_SOAPStructStruct,"return", 0);
		}
	}
	pCall->_functions->unInitialize(pCall->_object);
	return pReturn;
}


/*
 * This method wrap the service methodechoNestedArray
 */
SOAPArrayStruct* echoNestedArray(void* pStub, SOAPArrayStruct* Value0)
{
	Call* pCall = (Call*)pStub;
	SOAPArrayStruct* pReturn = NULL;
	/* Following will establish the connections with the server too */
	if (AXIS_SUCCESS != pCall->_functions->initialize(pCall->_object,C_RPC_PROVIDER, NORMAL_CHANNEL)) return pReturn;
	pCall->_functions->setTransportProperty(pCall->_object,SOAPACTION_HEADER , "cgroupB#echoNestedArray");
	pCall->_functions->setSOAPVersion(pCall->_object, SOAP_VER_1_1);
	pCall->_functions->setOperation(pCall->_object, "echoNestedArray", "http://soapinterop.org/");
	pCall->_functions->addCmplxParameter(pCall->_object, Value0, (void*)Axis_Serialize_SOAPArrayStruct, (void*)Axis_Delete_SOAPArrayStruct, "inputStruct", 0);
	if (AXIS_SUCCESS == pCall->_functions->invoke(pCall->_object))
	{
		if(AXIS_SUCCESS == pCall->_functions->checkMessage(pCall->_object, "echoNestedArrayResponse", ""))
		{
			pReturn = (SOAPArrayStruct*)pCall->_functions->getCmplxObject(pCall->_object, (void*) Axis_DeSerialize_SOAPArrayStruct, (void*) Axis_Create_SOAPArrayStruct, (void*) Axis_Delete_SOAPArrayStruct,"return", 0);
		}
	}
	pCall->_functions->unInitialize(pCall->_object);
	return pReturn;
}

