/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub Class for remote web service 
 */

#if !defined(__INTEROPTESTPORTTYPEB_H__INCLUDED_)
#define __INTEROPTESTPORTTYPEB_H__INCLUDED_

#include <axis/client/Stub.h>
#include <axis/server/AxisWrapperAPI.h>
#include "SOAPArrayStruct.h"
#include "SOAPStruct.h"
#include "SOAPStructStruct.h"

extern void* get_InteropTestPortTypeB_stub(const char* pchEndPointUri);
extern void destroy_InteropTestPortTypeB_stub(void* p);
extern int get_InteropTestPortTypeB_Status(void* pStub);
extern void echoStructAsSimpleTypes(void* pStub, SOAPStruct* Value0, AXIS_OUT_PARAM xsd__string *OutValue0, AXIS_OUT_PARAM int *OutValue1, AXIS_OUT_PARAM float *OutValue2);
extern SOAPStruct* echoSimpleTypesAsStruct(void* pStub, xsd__string Value0, int Value1, float Value2);
extern SOAPStructStruct* echoNestedStruct(void* pStub, SOAPStructStruct* Value0);
extern SOAPArrayStruct* echoNestedArray(void* pStub, SOAPArrayStruct* Value0);


#endif /* !defined(__INTEROPTESTPORTTYPEB_H__INCLUDED_) */
