/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type SOAPStructStruct
 */

#include <malloc.h>
#include "SOAPStructStruct.h"
#include <axis/server/AxisWrapperAPI.h>

extern int Axis_DeSerialize_SOAPStruct(SOAPStruct* param, IWrapperSoapDeSerializer* pDZ);
extern void* Axis_Create_SOAPStruct(SOAPStruct* pObj, bool bArray, int nSize);
extern void Axis_Delete_SOAPStruct(SOAPStruct* param, bool bArray, int nSize);
extern int Axis_Serialize_SOAPStruct(SOAPStruct* param, IWrapperSoapSerializer* pSZ, bool bArray);
extern int Axis_GetSize_SOAPStruct();

/**
 * This static method serialize a SOAPStructStruct type of object
 */
int Axis_Serialize_SOAPStructStruct(SOAPStructStruct* param, IWrapperSoapSerializer* pSZ, bool bArray)
{
	const AxisChar* sPrefix;
	if (bArray)
	{
		pSZ->_functions->serializeStartElementOfType(pSZ->_object, Axis_TypeName_SOAPStructStruct, 0, 0);
	}
	else
	{
		sPrefix = pSZ->_functions->getNamespacePrefix(pSZ->_object, Axis_URI_SOAPStructStruct);
		pSZ->_functions->serializeStartElementOfType(pSZ->_object, Axis_TypeName_SOAPStructStruct, Axis_URI_SOAPStructStruct, sPrefix);
	}

	pSZ->_functions->serializeAsElement(pSZ->_object, "SOAPStructStruct_varString", (void*)&(param->SOAPStructStruct_varString), XSD_STRING);
	pSZ->_functions->serializeAsElement(pSZ->_object, "SOAPStructStruct_varInt", (void*)&(param->SOAPStructStruct_varInt), XSD_INT);
	pSZ->_functions->serializeAsElement(pSZ->_object, "SOAPStructStruct_varFloat", (void*)&(param->SOAPStructStruct_varFloat), XSD_FLOAT);
	Axis_Serialize_SOAPStruct(param->SOAPStructStruct_varStruct, pSZ, false);

	pSZ->_functions->serializeEndElementOfType(pSZ->_object, Axis_TypeName_SOAPStructStruct);
	return AXIS_SUCCESS;
}

/**
 * This static method deserialize a SOAPStructStruct type of object
 */
int Axis_DeSerialize_SOAPStructStruct(SOAPStructStruct* param, IWrapperSoapDeSerializer* pDZ)
{
	param->SOAPStructStruct_varString = pDZ->_functions->getElementAsString(pDZ->_object,0,0);
	param->SOAPStructStruct_varInt = pDZ->_functions->getElementAsInt(pDZ->_object,0,0);
	param->SOAPStructStruct_varFloat = pDZ->_functions->getElementAsFloat(pDZ->_object,0,0);
	param->SOAPStructStruct_varStruct = (SOAPStruct*)pDZ->_functions->getCmplxObject(pDZ->_object, (void*)Axis_DeSerialize_SOAPStruct
		, (void*)Axis_Create_SOAPStruct, (void*)Axis_Delete_SOAPStruct
		, Axis_TypeName_SOAPStruct, Axis_URI_SOAPStruct);
	return pDZ->_functions->getStatus(pDZ->_object);
}
void* Axis_Create_SOAPStructStruct(SOAPStructStruct* pObj, bool bArray, int nSize)
{
	SOAPStructStruct* pTemp;
	if (bArray && (nSize > 0))
	{
		pObj = malloc(sizeof(SOAPStructStruct)*nSize);
			pTemp = pObj;
			pTemp += nSize/2;
			memset(pTemp, 0, sizeof(SOAPStructStruct)*nSize/2);
	}
	else
	{
		pObj = malloc(sizeof(SOAPStructStruct));
		memset(pObj, 0, sizeof(SOAPStructStruct));

		pTemp = pObj;
		pTemp->SOAPStructStruct_varStruct=0;
	}
	return pObj;
}
/**
 * This static method to deallocate a SOAPStructStruct type of object
 */
void Axis_Delete_SOAPStructStruct(SOAPStructStruct* param, bool bArray, int nSize)
{
	int x;
	SOAPStructStruct* pTemp;
	if (bArray)
	{
		/*delete any pointer members or array members of this struct here*/
		pTemp = param;
		for (x=0; x<nSize; x++)
		{
			if(pTemp->SOAPStructStruct_varString) free(pTemp->SOAPStructStruct_varString);
			if (pTemp->SOAPStructStruct_varStruct) Axis_Delete_SOAPStruct(pTemp->SOAPStructStruct_varStruct, false, 0);
			pTemp++;
		}
		free(param);
	}
	else
	{
		/*delete any pointer members or array members of this struct here*/
		if(param->SOAPStructStruct_varString) free(param->SOAPStructStruct_varString);
		if (param->SOAPStructStruct_varStruct) Axis_Delete_SOAPStruct(param->SOAPStructStruct_varStruct, false, 0);
		free(param);
	}
}
/**
 * This static method gives the size of SOAPStructStruct type of object
 */
int Axis_GetSize_SOAPStructStruct()
{
	return sizeof(SOAPStructStruct);
}
