/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains definitions of the web service
 */

#include "RefTestPortType.hpp"


RefTestPortType::RefTestPortType()
{
}

RefTestPortType::~RefTestPortType()
{
}

/* This function is called by the AxisEngine when something went wrong
 with the current web service request processing. Appropriate actions should
 be taken here.*/
void RefTestPortType::onFault()
{
}

intType* RefTestPortType::echoInt(intType* Value0)  
{
	return Value0;
}
