/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains the two export functions of the Web service Dynamic Library 
 */

#include "ExtensibilityQueryPortTypeWrapper.h" 
extern "C" {
STORAGE_CLASS_INFO
int GetClassInstance(BasicHandler **inst)
{
	*inst = new BasicHandler();
	WrapperClassHandler* pWCH = new ExtensibilityQueryPortTypeWrapper();
	(*inst)->_functions = 0;
	if (pWCH)
	{
		(*inst)->_object = pWCH;
		return pWCH->init();
	}
	return AXIS_FAIL;
}
STORAGE_CLASS_INFO 
int DestroyInstance(BasicHandler *inst)
{
	if (inst)
	{
		WrapperClassHandler* pWCH = reinterpret_cast<WrapperClassHandler*>(inst);
		pWCH->fini();
		delete pWCH;
		delete inst;
		return AXIS_SUCCESS;
	}
	return AXIS_FAIL;
}
}
