/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains definitions of the web service
 */

#include "ExtensibilityQueryPortType.h"


ExtensibilityQueryPortType::ExtensibilityQueryPortType()
{
}

ExtensibilityQueryPortType::~ExtensibilityQueryPortType()
{
}

AnyType* ExtensibilityQueryPortType::query(AnyType* Value0)
{
    return Value0;
}
