/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type intArrayType
 */

#if !defined(__INTARRAYTYPE_PARAM_H__INCLUDED_)
#define __INTARRAYTYPE_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

/*Local name and the URI for the type*/
static const char* Axis_URI_intArrayType = "http://soapinterop.org/xsd";
static const char* Axis_TypeName_intArrayType = "intArrayType";

class intArrayType
{
public:
	xsd__int_Array intItem;
	intArrayType();
	virtual ~intArrayType();
};

#endif /* !defined(__INTARRAYTYPE_PARAM_H__INCLUDED_)*/
