/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AxisCppContentHandler */

#ifndef _Included_AxisCppContentHandler
#define _Included_AxisCppContentHandler
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: DEBUG */
/*
 * Class:     AxisCppContentHandler
 * Method:    processContent
 * Signature: (Ljava/lang/StringBuffer;ILjava/util/Vector;I)V
 */
JNIEXPORT void JNICALL Java_AxisCppContentHandler_processContent
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jint);

JNIEXPORT jint JNICALL Java_OnLoad ( JavaVM *jvm, void *reserved);
JNIEXPORT void JNICALL Java_OnUnload ( JavaVM *jvm, void *reserved);


#ifdef __cplusplus
}
#endif
#endif
