package addressFetcher2;
/*This interface is automatically generated by 
*Axisj_lsf client service generator
*The client side representation of the web service. 
*/

public interface AddressBook extends java.rmi.Remote {
	public void addEntry(java.lang.String param0,addressFetcher2.Address param1)throws java.rmi.RemoteException;
	public addressFetcher2.Address getAddressFromName(java.lang.String param0)throws java.rmi.RemoteException;
}
