///////////////////////////////////////////////////////////////////////////////////
//This file is automatically generated by the Axis C++ Wrapper Class Generator
//Web service wrapper class's implementation generated by Axis WCG
//Parameters and wrapper methos to manipulate SOAPStructStruct
////////////////////////////////////////////////////////////////////////////////////

#if !defined(__SOAPSTRUCTSTRUCT_PARAM_H__OF_AXIS_INCLUDED_)
#define __SOAPSTRUCTSTRUCT_PARAM_H__OF_AXIS_INCLUDED_

#include <axis/server/AxisUserAPI.hpp>

#include "SOAPStruct.h"

AXIS_CPP_NAMESPACE_USE

//Local name and the URI for the type
static const char* Axis_URI_SOAPStructStruct = "http://soapinterop.org/xsd";
static const char* Axis_TypeName_SOAPStructStruct = "SOAPStructStruct";

class SOAPStructStruct
{
public:
	AxisChar* varString;
	int varInt;
	float varFloat;
	SOAPStruct* varStruct;
	SOAPStructStruct();
	~SOAPStructStruct();
};

#endif // !defined(__SOAPSTRUCTSTRUCT_PARAM_H__OF_AXIS_INCLUDED_)
