///////////////////////////////////////////////////////////////////////////////////
//This file is automatically generated by the Axis C++ Wrapper Class Generator
//Web service wrapper class's implementation generated by Axis WCG
//Parameters and wrapper methos to manipulate SOAPArrayStruct
////////////////////////////////////////////////////////////////////////////////////

#include "SOAPArrayStruct.h"
#include <axis/AxisWrapperAPI.hpp>

/////////////////////////////////////////////////////////////////////////////
// This static method serialize a SOAPArrayStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_Serialize_SOAPArrayStruct(SOAPArrayStruct* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	/* first serialize attributes if any*/
	pSZ->serialize(">", 0);
	/* then serialize elements if any*/
	pSZ->serializeAsElement("varString", (void*)&(param->varString), XSD_STRING);
	pSZ->serializeAsElement("varInt", (void*)&(param->varInt), XSD_INT);
	pSZ->serializeAsElement("varFloat", (void*)&(param->varFloat), XSD_FLOAT);
	pSZ->serializeBasicArray((Axis_Array*)(&param->varArray),XSD_STRING, "varArray");
	return AXIS_SUCCESS;
}

/////////////////////////////////////////////////////////////////////////////
// This static method deserialize a SOAPArrayStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_DeSerialize_SOAPArrayStruct(SOAPArrayStruct* param, IWrapperSoapDeSerializer *pIWSDZ)
{
	param->varString = pIWSDZ->getElementAsString("varString",0);
	param->varInt = pIWSDZ->getElementAsInt("varInt",0);
	param->varFloat = pIWSDZ->getElementAsFloat("varFloat",0);
	param->varArray = (ArrayOfstring&)pIWSDZ->getBasicArray(XSD_STRING,"varArray",0);
	return AXIS_SUCCESS;
}
void* Axis_Create_SOAPArrayStruct(void* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
		return new SOAPArrayStruct[nSize];
	else
		return new SOAPArrayStruct;
}

SOAPArrayStruct::SOAPArrayStruct()
{
	varString = 0;
	varArray.m_Array = 0;
	varArray.m_Size = 0;
}

SOAPArrayStruct::~SOAPArrayStruct()
{
	free(varString);
	delete varArray.m_Array;
}
/////////////////////////////////////////////////////////////////////////////
// This static method delete a SOAPArrayStruct type of object
//////////////////////////////////////////////////////////////////////
void Axis_Delete_SOAPArrayStruct(SOAPArrayStruct* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/////////////////////////////////////////////////////////////////////////////
// This static method gives the size of SOAPArrayStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_GetSize_SOAPArrayStruct()
{
	return sizeof(SOAPArrayStruct);
}
