// Copyright 2003-2004 The Apache Software Foundation.
// (c) Copyright IBM Corp. 2004, 2005 All Rights Reserved
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///////////////////////////////////////////////////////////////////////////////////
//This file is automatically generated by the Axis C++ Wrapper Class Generator
//Web service wrapper class's implementation generated by Axis WCG
//Parameters and wrapper methos to manipulate SOAPStructStruct
////////////////////////////////////////////////////////////////////////////////////

#if !defined(__SOAPSTRUCTSTRUCT_PARAM_H__OF_AXIS_INCLUDED_)
#define __SOAPSTRUCTSTRUCT_PARAM_H__OF_AXIS_INCLUDED_

#include <axis/AxisUserAPI.hpp>

#include "SOAPStruct.h"

AXIS_CPP_NAMESPACE_USE

//Local name and the URI for the type
static const char* Axis_URI_SOAPStructStruct = "http://soapinterop.org/xsd";
static const char* Axis_TypeName_SOAPStructStruct = "SOAPStructStruct";

class SOAPStructStruct
{
public:
	AxisChar* varString;
	int varInt;
	float varFloat;
	SOAPStruct* varStruct;
	SOAPStructStruct();
	~SOAPStructStruct();
};

#endif // !defined(__SOAPSTRUCTSTRUCT_PARAM_H__OF_AXIS_INCLUDED_)
