/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains definitions of the web service
 */

#include "pt1.hpp"


pt1::pt1()
{
}

pt1::~pt1()
{
}

/* This function is called by the AxisEngine when something went wrong
 with the current web service request processing. Appropriate actions should
 be taken here.*/
void pt1::onFault()
{
}
/* This function is called by the AxisEngine when this web service
 library is first loaded. So here we can initialize any global/static
 data structures of this web service or open database connections */
void pt1::init()
{
}
/* This function is called by the AxisEngine when this web service
 library is unloaded. So we can deallocate any global/static data structures
 and close database connections etc here. */
void pt1::fini()
{
}
/*xsd__base64Binary pt1::EchoAttachment(xsd__base64Binary Value0)  
{
	return Value0;
}
*/

ISoapAttachment* pt1::EchoAttachment(ISoapAttachment* objSoapAttach)
{
	return objSoapAttach;
}
