/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains implementations of an Exception class of the web service.
 */

#include "AxisNormalDetailException.h"

#include <axis/server/AxisWrapperAPI.h>

AxisNormalDetailException::AxisNormalDetailException()
{
/* This only serves the pupose of indicating that the 
 * service has thrown an excpetion 
 */ 
	m_iExceptionCode = AXISC_SERVICE_THROWN_EXCEPTION; 
	processException(m_iExceptionCode); 
}

AxisNormalDetailException::AxisNormalDetailException(SpecialDetailStruct*pFault)
{
	m_iExceptionCode = AXISC_SERVICE_THROWN_EXCEPTION;
	processException(pFault);}

AxisNormalDetailException::AxisNormalDetailException(int iExceptionCode)
{

	m_iExceptionCode = iExceptionCode;
	processException (iExceptionCode);
}

AxisNormalDetailException::AxisNormalDetailException(exception* e)
{
	processException (e);
}

AxisNormalDetailException::AxisNormalDetailException(exception* e,int iExceptionCode)
{

	processException (e, iExceptionCode);
}

AxisNormalDetailException::~AxisNormalDetailException() throw () 
{
	m_sMessage ="";
}

void AxisNormalDetailException:: processException(exception* e, int iExceptionCode)
{
	m_sMessage = getMessage (e) + getMessage (iExceptionCode);
}

void AxisNormalDetailException::processException (SpecialDetailStruct* pFault)
{
	/*User can do something like deserializing the struct into a string*/
        int iSize = strlen(pFault->varString) + 8;
        char* sMessage = new char[iSize];
        m_sMessage = new char[iSize];
        strcpy(sMessage, pFault->varString);
        strcat(sMessage, "\n");
                                                                                                                             
        m_sMessage = sMessage;
        delete(sMessage);
}

void AxisNormalDetailException::processException(exception* e)
{
	m_sMessage = getMessage (e);
}

void AxisNormalDetailException::processException(int iExceptionCode)
{
	m_sMessage = getMessage (iExceptionCode);
}

const string AxisNormalDetailException::getMessage (exception* objException)
{
	string sMessage = objException->what();
	return sMessage;
}

const string AxisNormalDetailException::getMessage (int iExceptionCode)
{
	string sMessage;
	switch(iExceptionCode)
	{
		case AXISC_SERVICE_THROWN_EXCEPTION:
		sMessage = "A service has thrown an exception. see detail";
		break;
		default:
		sMessage = "Unknown Exception has occured";
	}
return sMessage;
}

const char* AxisNormalDetailException::what() throw ()
{
	return m_sMessage.c_str ();
}

const int AxisNormalDetailException::getExceptionCode(){
	return m_iExceptionCode;
}

