/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains an Exception class of the web service.
 */

#if !defined(__AXISOUTOFBOUNDEXCEPTION_EXCEPTION_H__INCLUDED_)
#define __AXISOUTOFBOUNDEXCEPTION_EXCEPTION_H__INCLUDED_

#include <string>
#include <exception>
#include <axis/server/AxisException.h>
#include "OutOfBoundStruct.h"

using namespace std;
class AxisOutOfBoundException: public AxisException
{
public:
	AxisOutOfBoundException();
	AxisOutOfBoundException(OutOfBoundStruct* pFault);
	AxisOutOfBoundException(int iExceptionCode);
	AxisOutOfBoundException(exception* e);
	AxisOutOfBoundException(exception* e, int iExceptionCode);
	virtual ~AxisOutOfBoundException() throw();
	 const char* what() throw();
	 const int getExceptionCode();
	 const string getMessage(exception* e);
	 const string getMessage(int iExceptionCode);
private:
	 void processException(exception* e);
	 void processException(OutOfBoundStruct* pFault);
	 void processException(exception* e, int iExceptionCode);
	 void processException(int iExceptionCode);
	 string m_sMessage;
	 int m_iExceptionCode;

};

#endif /* !defined(__AXISOUTOFBOUNDEXCEPTION_EXCEPTION_H__INCLUDED_)*/
