/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type DivByZeroStruct
 */

#if !defined(__DIVBYZEROSTRUCT_PARAM_H__INCLUDED_)
#define __DIVBYZEROSTRUCT_PARAM_H__INCLUDED_

#include <axis/server/AxisUserAPI.hpp>

AXIS_CPP_NAMESPACE_USE

/*Local name and the URI for the type*/
static const char* Axis_URI_DivByZeroStruct = "http://soapinterop.org/types";
static const char* Axis_TypeName_DivByZeroStruct = "DivByZeroStruct";

class DivByZeroStruct
{
public:
	xsd__string varString;
	int varInt;
	float varFloat;
	DivByZeroStruct();
	virtual ~DivByZeroStruct();
};

#endif /* !defined(__DIVBYZEROSTRUCT_PARAM_H__INCLUDED_)*/
