/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains implementations of the MathOps Exception class of the web service.
 */

#include "MathOps_AxisClientException.hpp"

#include <axis/AxisWrapperAPI.hpp>

MathOps_AxisClientException::MathOps_AxisClientException()
{
/* This only serves the purpose of indicating that the 
 * service has thrown an excpetion 
 */ 
	m_iExceptionCode = AXISC_SERVICE_THROWN_EXCEPTION; 
	processException(m_iExceptionCode); 
}

MathOps_AxisClientException::MathOps_AxisClientException(ISoapFault* pFault)
{
	m_iExceptionCode = AXISC_SERVICE_THROWN_EXCEPTION;
	m_pISoapFault = pFault;
	processException(pFault);}

MathOps_AxisClientException::MathOps_AxisClientException(int iExceptionCode)
{

	m_iExceptionCode = iExceptionCode;
	processException (iExceptionCode);
}

MathOps_AxisClientException::MathOps_AxisClientException(exception* e)
{
	processException (e);
}

MathOps_AxisClientException::MathOps_AxisClientException(exception* e,int iExceptionCode)
{

	processException (e, iExceptionCode);
}

MathOps_AxisClientException::MathOps_AxisClientException(string sMessage)
{
	 m_sMessage =sMessage;
}

MathOps_AxisClientException::~MathOps_AxisClientException() throw () 
{
	m_sMessage ="";
}

void MathOps_AxisClientException:: processException(exception* e, int iExceptionCode)
{
	m_sMessage = getMessage (e) + getMessage (iExceptionCode);
}

void MathOps_AxisClientException::processException (ISoapFault* pFault)
{
	/*User can do something like deserializing the struct into a string*/
}

void MathOps_AxisClientException::processException(exception* e)
{
	m_sMessage = getMessage (e);
}

void MathOps_AxisClientException::processException(int iExceptionCode)
{
	m_sMessage = getMessage (iExceptionCode);
}

const string MathOps_AxisClientException::getMessage (exception* objException)
{
	string sMessage = objException->what();
	return sMessage;
}

const string MathOps_AxisClientException::getMessage (int iExceptionCode)
{
	string sMessage;
	switch(iExceptionCode)
	{
		case AXISC_SERVICE_THROWN_EXCEPTION:
		sMessage = "The MathOps service has thrown an exception. see details";
		break;
		default:
		sMessage = "Unknown Exception has occured in the MathOps service";
	}
return sMessage;
}

const char* MathOps_AxisClientException::what() throw ()
{
	return m_sMessage.c_str ();
}

const int MathOps_AxisClientException::getExceptionCode(){
	return m_iExceptionCode;
}

const ISoapFault* MathOps_AxisClientException::getFault(){
	return m_pISoapFault;
}

