package arrayCalc;
/*This class is automatically generated by 
*axis_lsf client service generator
*The client side Locator of the web service. 
*/

public class ArrayCalcLocator  {

	private arrayCalc.ArrayCalc ws;
	public ArrayCalcLocator(){
	}
	public ArrayCalcLocator(java.lang.String enduri){
	this.ws = new arrayCalc.ArrayCalcStub(enduri);
	}

	public arrayCalc.ArrayCalc getStub(){
		return this.ws;
	}
}
