package xmltoday_delayed_quotes;
/*This interface is automatically generated by 
*Axisj_lsf client service generator
*The client side representation of the web service. 
*/

public interface GetQuote extends java.rmi.Remote {
	public float getQuote(java.lang.String param0)throws java.rmi.RemoteException;
	public java.lang.String test()throws java.rmi.RemoteException;
}
