# Makefile.in generated automatically by automake 1.5 from Makefile.am.
# Generated automatically from Makefile.in by config.pl.
# KDE tags expanded automatically by am_edit - $Revision$ 

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



####### kdevelop will overwrite this part!!! (begin)##########

SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
VPATH = .
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = /home/damitha/projects/axiscpp/c/release
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/src
pkglibdir = $(libdir)/src
pkgincludedir = $(includedir)/src
top_builddir = ../..

ACLOCAL = ${SHELL} /home/damitha/projects/axiscpp/c/admin/missing --run aclocal
AUTOCONF = ${SHELL} /home/damitha/projects/axiscpp/c/admin/missing --run autoconf
AUTOMAKE = ${SHELL} /home/damitha/projects/axiscpp/c/admin/missing --run automake
AUTOHEADER = ${SHELL} /home/damitha/projects/axiscpp/c/admin/missing --run autoheader

INSTALL = /usr/bin/install -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,^,i386-linux-,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i386-linux
build_triplet = i386-pc-linux-gnu
host_alias = i386-linux
host_triplet = i386-pc-linux-gnu
target_alias = i386-linux
target_triplet = i386-pc-linux-gnu
AMTAR = ${SHELL} /home/damitha/projects/axiscpp/c/admin/missing --run tar
ARTSCCONFIG = @ARTSCCONFIG@
AS = @AS@
AUTODIRS = 
AWK = gawk
CC = gcc
CONF_FILES =  $(top_srcdir)/configure.in.in
CPP = cpp
CXX = g++
CXXCPP = g++ -E
DCOPIDL = @DCOPIDL@
DCOPIDL2CPP = @DCOPIDL2CPP@
DCOP_DEPENDENCIES = @DCOP_DEPENDENCIES@
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
DOXYGEN = @DOXYGEN@
DOXYGEN_PROJECT_NAME = @DOXYGEN_PROJECT_NAME@
DOXYGEN_PROJECT_NUMBER = @DOXYGEN_PROJECT_NUMBER@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
ECHO = echo
EXEEXT = 
FRAMEWORK_COREAUDIO = @FRAMEWORK_COREAUDIO@
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = @GMSGFMT@
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = @KDECONFIG@
KDE_EXTRA_RPATH = @KDE_EXTRA_RPATH@
KDE_HAS_DOXYGEN = @KDE_HAS_DOXYGEN@
KDE_HAVE_DOT = @KDE_HAVE_DOT@
KDE_INCLUDES = @KDE_INCLUDES@
KDE_LDFLAGS = @KDE_LDFLAGS@
KDE_MT_LDFLAGS = @KDE_MT_LDFLAGS@
KDE_MT_LIBS = @KDE_MT_LIBS@
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH) $(KDE_MT_LDFLAGS)
KDE_RPATH = @KDE_RPATH@
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KDE_XSL_STYLESHEET = @KDE_XSL_STYLESHEET@
LEX = @LEX@
LEXLIB = @LEXLIB@
LIBCOMPAT = @LIBCOMPAT@
LIBCRYPT = @LIBCRYPT@
LIBDL = @LIBDL@
LIBGEN = @LIBGEN@
LIBJPEG = @LIBJPEG@
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = @LIBPNG@
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBRESOLV = @LIBRESOLV@
LIBSHADOW = @LIBSHADOW@
LIBSM = @LIBSM@
LIBSOCKET = @LIBSOCKET@
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool --silent
LIBUCB = @LIBUCB@
LIBUTIL = @LIBUTIL@
LIBXINERAMA = @LIBXINERAMA@
LIBZ = @LIBZ@
LIB_KAB = @LIB_KAB@
LIB_KDECORE = @LIB_KDECORE@
LIB_KDEPRINT = @LIB_KDEPRINT@
LIB_KDEUI = @LIB_KDEUI@
LIB_KFILE = @LIB_KFILE@
LIB_KFM = @LIB_KFM@
LIB_KHTML = @LIB_KHTML@
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = @LIB_KIO@
LIB_KPARTS = @LIB_KPARTS@
LIB_KSPELL = @LIB_KSPELL@
LIB_KSYCOCA = @LIB_KSYCOCA@
LIB_POLL = @LIB_POLL@
LIB_QPE = @LIB_QPE@
LIB_QT = @LIB_QT@
LIB_QTOPIA = @LIB_QTOPIA@
LIB_SMB = @LIB_SMB@
LIB_X11 = @LIB_X11@
LIB_XEXT = @LIB_XEXT@
LN_S = ln -s
MCOPIDL = @MCOPIDL@
MEINPROC = @MEINPROC@
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = @MOC@
MSGFMT = @MSGFMT@
NOOPT_CFLAGS = -O0
NOOPT_CXXFLAGS = -O0
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = src
PAMLIBS = @PAMLIBS@
PASSWDLIBS = @PASSWDLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
PYTHONMODDIR = @PYTHONMODDIR@
QTDOCDIR = @QTDOCDIR@
QTE_NORTTI = @QTE_NORTTI@
QTOPIA_INCLUDES = @QTOPIA_INCLUDES@
QT_INCLUDES = @QT_INCLUDES@
QT_LDFLAGS = @QT_LDFLAGS@
RANLIB = ranlib
RC = @RC@
REPO = -frepo
SETUIDFLAGS = @SETUIDFLAGS@
STRIP = strip
TOPSUBDIRS =  src
UIC = @UIC@
UIC_TR = @UIC_TR@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = 
USE_THREADS = @USE_THREADS@
VERSION = 0.1
WOVERLOADED_VIRTUAL = -Woverloaded-virtual
XGETTEXT = @XGETTEXT@
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = @X_EXTRA_LIBS@
X_INCLUDES = @X_INCLUDES@
X_LDFLAGS = @X_LDFLAGS@
X_PRE_LIBS = @X_PRE_LIBS@
all_includes =   -I/usr/local/apache/include -I/include
all_libraries =  
am__include = include
am__quote = 
idldir = @idldir@
install_sh = /home/damitha/projects/axiscpp/c/admin/install-sh
jni_includes = @jni_includes@
kde_appsdir = @kde_appsdir@
kde_bindir = @kde_bindir@
kde_confdir = @kde_confdir@
kde_datadir = @kde_datadir@
kde_htmldir = @kde_htmldir@
kde_icondir = @kde_icondir@
kde_includes = @kde_includes@
kde_libraries = @kde_libraries@
kde_libs_htmldir = @kde_libs_htmldir@
kde_libs_prefix = @kde_libs_prefix@
kde_locale = @kde_locale@
kde_mimedir = @kde_mimedir@
kde_moduledir = @kde_moduledir@
kde_qtver = @kde_qtver@
kde_servicesdir = @kde_servicesdir@
kde_servicetypesdir = @kde_servicetypesdir@
kde_sounddir = @kde_sounddir@
kde_styledir = @kde_styledir@
kde_templatesdir = @kde_templatesdir@
kde_wallpaperdir = @kde_wallpaperdir@
kde_widgetdir = @kde_widgetdir@
micodir = @micodir@
qt_includes = @qt_includes@
qt_libraries = @qt_libraries@
x_includes = @x_includes@
x_libraries = @x_libraries@

noinst_LIBRARIES = libsoap.a

INCLUDES = $(all_includes)

#>- libsoap_a_METASOURCES = AUTO

libsoap_a_SOURCES = XMLStreamHandler.cpp URIMapping.cpp SoapSerializer.cpp SoapMethod.cpp SoapHeader.cpp SoapFault.cpp SoapEnvelope.cpp SoapDeSerializer.cpp SoapBody.cpp HeaderEntry.cpp HeaderBlock.cpp ComplexElement.cpp CharacterElement.cpp BasicNode.cpp Attribute.cpp 

EXTRA_DIST = Attribute.cpp Attribute.h BasicNode.cpp BasicNode.h CharacterElement.cpp CharacterElement.h ComplexElement.cpp ComplexElement.h HeaderBlock.cpp HeaderBlock.h HeaderEntry.cpp HeaderEntry.h SoapBody.cpp SoapBody.h SoapDeSerializer.cpp SoapDeSerializer.h SoapEnvelope.cpp SoapEnvelope.h SoapEnvVersions.h SoapFault.cpp SoapFault.h SoapFaults.h SoapHeader.cpp SoapHeader.h SoapMethod.cpp SoapMethod.h SoapSerializer.cpp SoapSerializer.h URIMapping.cpp URIMapping.h XMLStreamHandler.cpp XMLStreamHandler.h 
subdir = src/soap
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
LIBRARIES = $(noinst_LIBRARIES)

libsoap_a_AR = $(AR) cru
libsoap_a_LIBADD =
am_libsoap_a_OBJECTS = XMLStreamHandler.$(OBJEXT) URIMapping.$(OBJEXT) \
	SoapSerializer.$(OBJEXT) SoapMethod.$(OBJEXT) \
	SoapHeader.$(OBJEXT) SoapFault.$(OBJEXT) SoapEnvelope.$(OBJEXT) \
	SoapDeSerializer.$(OBJEXT) SoapBody.$(OBJEXT) \
	HeaderEntry.$(OBJEXT) HeaderBlock.$(OBJEXT) \
	ComplexElement.$(OBJEXT) CharacterElement.$(OBJEXT) \
	BasicNode.$(OBJEXT) Attribute.$(OBJEXT)
#>- libsoap_a_OBJECTS = $(am_libsoap_a_OBJECTS)
#>+ 10
libsoap_a_final_OBJECTS = libsoap_a.all_cpp.o 
libsoap_a_nofinal_OBJECTS = XMLStreamHandler.$(OBJEXT) URIMapping.$(OBJEXT) \
	SoapSerializer.$(OBJEXT) SoapMethod.$(OBJEXT) \
	SoapHeader.$(OBJEXT) SoapFault.$(OBJEXT) SoapEnvelope.$(OBJEXT) \
	SoapDeSerializer.$(OBJEXT) SoapBody.$(OBJEXT) \
	HeaderEntry.$(OBJEXT) HeaderBlock.$(OBJEXT) \
	ComplexElement.$(OBJEXT) CharacterElement.$(OBJEXT) \
	BasicNode.$(OBJEXT) Attribute.$(OBJEXT)
libsoap_a_OBJECTS = $(libsoap_a_nofinal_OBJECTS)
#libsoap_a_OBJECTS = $(libsoap_a_final_OBJECTS)

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS = 
LDFLAGS = 
LIBS = 
depcomp = $(SHELL) $(top_srcdir)/admin/depcomp
#>- DEP_FILES = $(DEPDIR)/Attribute.Po $(DEPDIR)/BasicNode.Po \
#>- 	$(DEPDIR)/CharacterElement.Po \
#>- 	$(DEPDIR)/ComplexElement.Po \
#>- 	$(DEPDIR)/HeaderBlock.Po $(DEPDIR)/HeaderEntry.Po \
#>- 	$(DEPDIR)/SoapBody.Po $(DEPDIR)/SoapDeSerializer.Po \
#>- 	$(DEPDIR)/SoapEnvelope.Po $(DEPDIR)/SoapFault.Po \
#>- 	$(DEPDIR)/SoapHeader.Po $(DEPDIR)/SoapMethod.Po \
#>- 	$(DEPDIR)/SoapSerializer.Po $(DEPDIR)/URIMapping.Po \
#>- 	$(DEPDIR)/XMLStreamHandler.Po
#>+ 19
#DEP_FILES =   $(DEPDIR)/libsoap_a.all_cpp.P  $(DEPDIR)/Attribute.Po $(DEPDIR)/BasicNode.Po \
		$(DEPDIR)/CharacterElement.Po \
		$(DEPDIR)/ComplexElement.Po \
		$(DEPDIR)/HeaderBlock.Po $(DEPDIR)/HeaderEntry.Po \
		$(DEPDIR)/SoapBody.Po $(DEPDIR)/SoapDeSerializer.Po \
		$(DEPDIR)/SoapEnvelope.Po $(DEPDIR)/SoapFault.Po \
		$(DEPDIR)/SoapHeader.Po $(DEPDIR)/SoapMethod.Po \
		$(DEPDIR)/SoapSerializer.Po $(DEPDIR)/URIMapping.Po \
		$(DEPDIR)/XMLStreamHandler.Po
DEP_FILES =   $(DEPDIR)/Attribute.Po $(DEPDIR)/BasicNode.Po \
		$(DEPDIR)/CharacterElement.Po \
		$(DEPDIR)/ComplexElement.Po \
		$(DEPDIR)/HeaderBlock.Po $(DEPDIR)/HeaderEntry.Po \
		$(DEPDIR)/SoapBody.Po $(DEPDIR)/SoapDeSerializer.Po \
		$(DEPDIR)/SoapEnvelope.Po $(DEPDIR)/SoapFault.Po \
		$(DEPDIR)/SoapHeader.Po $(DEPDIR)/SoapMethod.Po \
		$(DEPDIR)/SoapSerializer.Po $(DEPDIR)/URIMapping.Po \
		$(DEPDIR)/XMLStreamHandler.Po

#>- CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
#>- $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 2
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) \
#>- $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
#>- $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 3
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
#>- $(AM_LDFLAGS) $(LDFLAGS) -o $@
#>+ 2
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CXXFLAGS = -Wnon-virtual-dtor -Wno-long-long -Wbad-function-cast -Wundef -Wall -pedantic -W -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -ansi -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -Wcast-align -Wconversion -fno-builtin -g -O2 -O0 -g3 -Wall -fPIC -fno-exceptions -fno-check-new -fexceptions
DIST_SOURCES = $(libsoap_a_SOURCES)
DIST_COMMON = Makefile.am Makefile.in
SOURCES = $(libsoap_a_SOURCES)

#>- all: all-am
#>+ 1
all: docs-am  all-am

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
#>- 	cd $(top_srcdir) && \
#>- $(AUTOMAKE) --gnu  src/soap/Makefile
#>+ 3
	cd $(top_srcdir) && \
	$(AUTOMAKE) --gnu  src/soap/Makefile
	cd $(top_srcdir) && perl admin/am_edit src/soap/Makefile.in
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	CONFIG_HEADERS= CONFIG_LINKS= \
	CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status

AR = ar

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
libsoap.a: $(libsoap_a_OBJECTS) $(libsoap_a_DEPENDENCIES) 
	-rm -f libsoap.a
	$(libsoap_a_AR) libsoap.a $(libsoap_a_OBJECTS) $(libsoap_a_LIBADD)
	$(RANLIB) libsoap.a

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/Attribute.Po
include $(DEPDIR)/BasicNode.Po
include $(DEPDIR)/CharacterElement.Po
include $(DEPDIR)/ComplexElement.Po
include $(DEPDIR)/HeaderBlock.Po
include $(DEPDIR)/HeaderEntry.Po
include $(DEPDIR)/SoapBody.Po
include $(DEPDIR)/SoapDeSerializer.Po
include $(DEPDIR)/SoapEnvelope.Po
include $(DEPDIR)/SoapFault.Po
include $(DEPDIR)/SoapHeader.Po
include $(DEPDIR)/SoapMethod.Po
include $(DEPDIR)/SoapSerializer.Po
include $(DEPDIR)/URIMapping.Po
include $(DEPDIR)/XMLStreamHandler.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.cpp.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cpp.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`

.cpp.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CXXDEPMODE) $(depcomp) \
	$(LTCXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CXXDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	done | \
	$(AWK) '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
	$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	done | \
	$(AWK) '    { files[$$0] = 1; } \
	END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	|| etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	&& cd $(top_srcdir) \
	&& gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

#>- DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=Attribute.h 

DISTFILES= $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


top_distdir = ../..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	if test -f $$file; then d=.; else d=$(srcdir); fi; \
	dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	$(mkinstalldirs) "$(distdir)/$$dir"; \
	fi; \
	if test -d $$d/$$file; then \
	cp -pR $$d/$$file $(distdir) \
	|| exit 1; \
	else \
	test -f $(distdir)/$$file \
	|| cp -p $$d/$$file $(distdir)/$$file \
	|| exit 1; \
	fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES)

installdirs:

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	`test -z '$(STRIP)' || \
	echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

#>- clean-am: clean-generic clean-libtool clean-noinstLIBRARIES \
#>- mostlyclean-am
#>+ 2
clean-am: clean-final  clean-generic clean-libtool clean-noinstLIBRARIES \
	mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am:

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-generic \
	clean-libtool clean-noinstLIBRARIES distclean distclean-compile \
	distclean-depend distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	tags uninstall uninstall-am uninstall-info-am


####### kdevelop will overwrite this part!!! (end)############
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 2
docs-am:

#>+ 6
force-reedit:
		cd $(top_srcdir) && \
	$(AUTOMAKE) --gnu  src/soap/Makefile
	cd $(top_srcdir) && perl admin/am_edit src/soap/Makefile.in


#>+ 11
libsoap_a.all_cpp.cpp: $(srcdir)/Makefile.in  $(srcdir)/XMLStreamHandler.cpp $(srcdir)/URIMapping.cpp $(srcdir)/SoapSerializer.cpp $(srcdir)/SoapMethod.cpp $(srcdir)/SoapHeader.cpp $(srcdir)/SoapFault.cpp $(srcdir)/SoapEnvelope.cpp $(srcdir)/SoapDeSerializer.cpp $(srcdir)/SoapBody.cpp $(srcdir)/HeaderEntry.cpp $(srcdir)/HeaderBlock.cpp $(srcdir)/ComplexElement.cpp $(srcdir)/CharacterElement.cpp $(srcdir)/BasicNode.cpp $(srcdir)/Attribute.cpp 
	@echo 'creating libsoap_a.all_cpp.cpp ...'; \
	rm -f libsoap_a.all_cpp.files libsoap_a.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> libsoap_a.all_cpp.final; \
	for file in XMLStreamHandler.cpp URIMapping.cpp SoapSerializer.cpp SoapMethod.cpp SoapHeader.cpp SoapFault.cpp SoapEnvelope.cpp SoapDeSerializer.cpp SoapBody.cpp HeaderEntry.cpp HeaderBlock.cpp ComplexElement.cpp CharacterElement.cpp BasicNode.cpp Attribute.cpp ; do \
	  echo "#include \"$$file\"" >> libsoap_a.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> libsoap_a.all_cpp.final; \
	done; \
	cat libsoap_a.all_cpp.final libsoap_a.all_cpp.files > libsoap_a.all_cpp.cpp; \
	rm -f libsoap_a.all_cpp.final libsoap_a.all_cpp.files

#>+ 3
clean-final:
	-rm -f libsoap_a.all_cpp.cpp

#>+ 2
final:
	$(MAKE) libsoap_a_OBJECTS="$(libsoap_a_final_OBJECTS)" all-am
#>+ 2
final-install:
	$(MAKE) libsoap_a_OBJECTS="$(libsoap_a_final_OBJECTS)" install-am
#>+ 2
no-final:
	$(MAKE) libsoap_a_OBJECTS="$(libsoap_a_nofinal_OBJECTS)" all-am
#>+ 2
no-final-install:
	$(MAKE) libsoap_a_OBJECTS="$(libsoap_a_nofinal_OBJECTS)" install-am
#>+ 3
cvs-clean:
	$(MAKE) admindir=$(top_srcdir)/admin -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo
