///////////////////////////////////////////////////////////////////////////////////
//This file is automatically generated by the Axis C++ Wrapper Class Generator
//Web service wrapper class's implementation generated by Axis WCG
//Parameters and wrapper methos to manipulate ArrayOfstring
////////////////////////////////////////////////////////////////////////////////////

#if !defined(__ARRAYOFSTRING_ARRAY_H__OF_AXIS_INCLUDED_)
#define __ARRAYOFSTRING_ARRAY_H__OF_AXIS_INCLUDED_

#include <axis/server/AxisUserAPI.h>

typedef struct ArrayOfstringTag
{
	char** m_Array;
	int m_Size;
} ArrayOfstring;

#endif // !defined(__ARRAYOFSTRING_ARRAY_H__OF_AXIS_INCLUDED_)
