//		This file is automatically generated by the Axis C++ Wrapper Class Generator
//		Service file containing the two export functions of the Web service Library
#ifdef WIN32
#define STORAGE_CLASS_INFO __declspec(dllexport)
#else
#define STORAGE_CLASS_INFO 
#endif
#include "InteropTestPortTypeBWrapper.h" 
extern "C" {
STORAGE_CLASS_INFO
int GetClassInstance(BasicHandler **inst)
{
	WrapperClassHandler* pWCH = new InteropTestPortTypeBWrapper();
	if (pWCH)
	{
		pWCH->Init();
		*inst = pWCH;
		return AXIS_SUCCESS;
	}
	return AXIS_FAIL;
}
STORAGE_CLASS_INFO 
int DestroyInstance(BasicHandler *inst)
{
	if (inst)
	{
		WrapperClassHandler* pWCH = static_cast<WrapperClassHandler*>(inst);
		pWCH->Fini();
		delete pWCH;
		return AXIS_SUCCESS;
	}
	return AXIS_FAIL;
}
}
