<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://soapinterop.org/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://soapinterop.org/types" targetNamespace="http://soapinterop.org/wsdl">
	<message name="divRequest">
		<part name="int0" type="xsd:int"/>
		<part name="int1" type="xsd:int"/>
	</message>
	<message name="divResponse">
		<part name="addReturn" type="xsd:int"/>
	</message>
	<portType name="MathOps">
		<operation name="div" parameterOrder ="int0 int1">
			<input message="tns:divRequest"/>
			<output message="tns:divResponse"/>
		 </operation>
	</portType>
	<binding name="MathOpsBinding" type="tns:MathOps">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="div">
			  <soap:operation soapAction="MathOps#div"/>
                <input name="divRequest">
                    <soap:body 
                        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" 
                        namespace="http://localhost/axis/MathOps" 
                        use="encoded"/>
                </input>
                <output name="divResponse">
                    <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" 
                        namespace="http://localhost/axis/MathOps" 
                        use="encoded"/>
                </output>
			</operation>
		</binding>
	<service name="MathOpsService">
		<port name="MathOps" binding="tns:MathOpsBinding">
			<soap:address location="http://localhost/axis/MathOps"/>
		</port>
	</service>
	<!-- Fault messages -->
</definitions>
