package com.bookshop.soap;
/*This class is automatically generated by 
*axis_lsf client stub generator
*The client side stub of the web service. 
*/

public class AmazonSearchPortStub implements com.bookshop.soap.AmazonSearchPort{

	private java.lang.String enduri;
	private javax.xml.namespace.QName SOAPAction;
	private org.apache.axismora.client.Service service;

	public AmazonSearchPortStub(){
	}
	public AmazonSearchPortStub(java.lang.String enduri){
		try{
			this.enduri = enduri;
			this.SOAPAction = new javax.xml.namespace.QName("-sboth");
			this.service = new org.apache.axismora.client.Service();
		}catch(Exception e){
			e.printStackTrace();
		}
	}

	public com.bookshop.soap.ProductInfo KeywordSearchRequest(com.bookshop.soap.KeywordRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("KeywordSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","KeywordRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo PowerSearchRequest(com.bookshop.soap.PowerRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("PowerSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","PowerRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo BrowseNodeSearchRequest(com.bookshop.soap.BrowseNodeRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("BrowseNodeSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","BrowseNodeRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo AsinSearchRequest(com.bookshop.soap.AsinRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("AsinSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","AsinRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductLine[] BlendedSearchRequest(com.bookshop.soap.BlendedRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("BlendedSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","BlendedRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductLineArray"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductLineArray res = (com.bookshop.soap.ProductLineArray)(new com.bookshop.soap.ProductLineArray()).desierialize(mx);
		 return (com.bookshop.soap.ProductLine[])res.getParam();

		}

	public com.bookshop.soap.ProductInfo UpcSearchRequest(com.bookshop.soap.UpcRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("UpcSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","UpcRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo AuthorSearchRequest(com.bookshop.soap.AuthorRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("AuthorSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","AuthorRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo ArtistSearchRequest(com.bookshop.soap.ArtistRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("ArtistSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","ArtistRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo ActorSearchRequest(com.bookshop.soap.ActorRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("ActorSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","ActorRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo ManufacturerSearchRequest(com.bookshop.soap.ManufacturerRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("ManufacturerSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","ManufacturerRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo DirectorSearchRequest(com.bookshop.soap.DirectorRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("DirectorSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","DirectorRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo ListManiaSearchRequest(com.bookshop.soap.ListManiaRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("ListManiaSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","ListManiaRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo WishlistSearchRequest(com.bookshop.soap.WishlistRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("WishlistSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","WishlistRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ListingProductDetails ExchangeSearchRequest(com.bookshop.soap.ExchangeRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("ExchangeSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","ExchangeRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ListingProductDetails"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ListingProductDetails res = (com.bookshop.soap.ListingProductDetails)(new com.bookshop.soap.ListingProductDetails()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.MarketplaceSearch MarketplaceSearchRequest(com.bookshop.soap.MarketplaceRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("MarketplaceSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","MarketplaceRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","MarketplaceSearch"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.MarketplaceSearch res = (com.bookshop.soap.MarketplaceSearch)(new com.bookshop.soap.MarketplaceSearch()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.SellerProfile SellerProfileSearchRequest(com.bookshop.soap.SellerProfileRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("SellerProfileSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","SellerProfileRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","SellerProfile"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.SellerProfile res = (com.bookshop.soap.SellerProfile)(new com.bookshop.soap.SellerProfile()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.SellerSearch SellerSearchRequest(com.bookshop.soap.SellerRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("SellerSearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","SellerRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","SellerSearch"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.SellerSearch res = (com.bookshop.soap.SellerSearch)(new com.bookshop.soap.SellerSearch()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ProductInfo SimilaritySearchRequest(com.bookshop.soap.SimilarityRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("SimilaritySearchRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","SimilarityRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ProductInfo"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ProductInfo res = (com.bookshop.soap.ProductInfo)(new com.bookshop.soap.ProductInfo()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ShoppingCart GetShoppingCartRequest(com.bookshop.soap.GetShoppingCartRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("GetShoppingCartRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","GetShoppingCartRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ShoppingCart"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ShoppingCart res = (com.bookshop.soap.ShoppingCart)(new com.bookshop.soap.ShoppingCart()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ShoppingCart ClearShoppingCartRequest(com.bookshop.soap.ClearShoppingCartRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("ClearShoppingCartRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","ClearShoppingCartRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ShoppingCart"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ShoppingCart res = (com.bookshop.soap.ShoppingCart)(new com.bookshop.soap.ShoppingCart()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ShoppingCart AddShoppingCartItemsRequest(com.bookshop.soap.AddShoppingCartItemsRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("AddShoppingCartItemsRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","AddShoppingCartItemsRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ShoppingCart"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ShoppingCart res = (com.bookshop.soap.ShoppingCart)(new com.bookshop.soap.ShoppingCart()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ShoppingCart RemoveShoppingCartItemsRequest(com.bookshop.soap.RemoveShoppingCartItemsRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("RemoveShoppingCartItemsRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","RemoveShoppingCartItemsRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ShoppingCart"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ShoppingCart res = (com.bookshop.soap.ShoppingCart)(new com.bookshop.soap.ShoppingCart()).desierialize(mx);
		 return res;

		}

	public com.bookshop.soap.ShoppingCart ModifyShoppingCartItemsRequest(com.bookshop.soap.ModifyShoppingCartItemsRequest param0)throws java.rmi.RemoteException{
		javax.xml.namespace.QName methodName = new javax.xml.namespace.QName("ModifyShoppingCartItemsRequest");
		org.apache.axismora.client.Call call = (org.apache.axismora.client.Call)service.createCall();
		call.setOperationName(methodName);
		call.setPortTypeName(SOAPAction);
		call.addParameter("param0",new javax.xml.namespace.QName("http://soap.bookshop.com","ModifyShoppingCartItemsRequest"),javax.xml.rpc.ParameterMode.IN);
		call.setTargetEndpointAddress(this.enduri);
		call.setReturnType(new javax.xml.namespace.QName("http://soap.bookshop.com","ShoppingCart"));
		org.apache.axismora.MessageContext mx = (org.apache.axismora.MessageContext)call.invokeLowLevel(methodName,new org.apache.axismora.encoding.OutParameter[]{param0});
		com.bookshop.soap.ShoppingCart res = (com.bookshop.soap.ShoppingCart)(new com.bookshop.soap.ShoppingCart()).desierialize(mx);
		 return res;

		}
}
