// Copyright 2003-2004 The Apache Software Foundation.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//        http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Web Service Wrapper declarations
 */

#if !defined(__INTEROPTESTPORTTYPEBWRAPPER_H__INCLUDED_)
#define __INTEROPTESTPORTTYPEBWRAPPER_H__INCLUDED_

#include <axis/server/IMessageData.h>
#include <axis/server/AxisWrapperAPI.h>

/*implementation of BasicHandler interface*/
int AXISCALL InteropTestPortTypeBWrapper_Invoke(void*p, void* pMsg);
void AXISCALL InteropTestPortTypeBWrapper_OnFault(void*p, void* pMsg);
int AXISCALL InteropTestPortTypeBWrapper_Init(void*p);
int AXISCALL InteropTestPortTypeBWrapper_Fini(void*p);
int AXISCALL InteropTestPortTypeBWrapper_GetType(void*p);
AXIS_BINDING_STYLE AXISCALL InteropTestPortTypeBWrapper_GetBindingStyle(void*p);
/*Methods corresponding to the web service methods*/
int echoStructAsSimpleTypesWrapped(IWrapperSoapDeSerializer DZ, IWrapperSoapSerializer SZ);
int echoSimpleTypesAsStructWrapped(IWrapperSoapDeSerializer DZ, IWrapperSoapSerializer SZ);
int echoNestedStructWrapped(IWrapperSoapDeSerializer DZ, IWrapperSoapSerializer SZ);
int echoNestedArrayWrapped(IWrapperSoapDeSerializer DZ, IWrapperSoapSerializer SZ);


#endif /* !defined(__INTEROPTESTPORTTYPEBWRAPPER_H__INCLUDED_) */
