/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type SOAPArrayStruct
 */

#include <malloc.h>
#include "SOAPArrayStruct.h"
#include <axis/server/AxisWrapperAPI.h>

/**
 * This static method serialize a SOAPArrayStruct type of object
 */
int Axis_Serialize_SOAPArrayStruct(SOAPArrayStruct* param, IWrapperSoapSerializer* pSZ, bool bArray)
{
	const AxisChar* sPrefix;
	if (bArray)
	{
		pSZ->_functions->serializeStartElementOfType(pSZ->_object, Axis_TypeName_SOAPArrayStruct, 0, 0);
	}
	else
	{
		sPrefix = pSZ->_functions->getNamespacePrefix(pSZ->_object, Axis_URI_SOAPArrayStruct);
		pSZ->_functions->serializeStartElementOfType(pSZ->_object, Axis_TypeName_SOAPArrayStruct, Axis_URI_SOAPArrayStruct, sPrefix);
	}

	pSZ->_functions->serializeAsElement(pSZ->_object, "SOAPArrayStruct_varString", (void*)&(param->SOAPArrayStruct_varString), XSD_STRING);
	pSZ->_functions->serializeAsElement(pSZ->_object, "SOAPArrayStruct_varInt", (void*)&(param->SOAPArrayStruct_varInt), XSD_INT);
	pSZ->_functions->serializeAsElement(pSZ->_object, "SOAPArrayStruct_varFloat", (void*)&(param->SOAPArrayStruct_varFloat), XSD_FLOAT);
	pSZ->_functions->serializeBasicArray(pSZ->_object, (Axis_Array*)(&param->SOAPArrayStruct_varArray),XSD_STRING, "SOAPArrayStruct_varArray");

	pSZ->_functions->serializeEndElementOfType(pSZ->_object, Axis_TypeName_SOAPArrayStruct);
	return AXIS_SUCCESS;
}

/**
 * This static method deserialize a SOAPArrayStruct type of object
 */
int Axis_DeSerialize_SOAPArrayStruct(SOAPArrayStruct* param, IWrapperSoapDeSerializer* pDZ)
{
	Axis_Array array;
	param->SOAPArrayStruct_varString = pDZ->_functions->getElementAsString(pDZ->_object,0,0);
	param->SOAPArrayStruct_varInt = pDZ->_functions->getElementAsInt(pDZ->_object,0,0);
	param->SOAPArrayStruct_varFloat = pDZ->_functions->getElementAsFloat(pDZ->_object,0,0);
	array = pDZ->_functions->getBasicArray(pDZ->_object, XSD_STRING,0,0);
	memcpy(&(param->SOAPArrayStruct_varArray), &array, sizeof(Axis_Array));
	return pDZ->_functions->getStatus(pDZ->_object);
}
void* Axis_Create_SOAPArrayStruct(SOAPArrayStruct* pObj, bool bArray, int nSize)
{
	SOAPArrayStruct* pTemp;
	if (bArray && (nSize > 0))
	{
		pObj = malloc(sizeof(SOAPArrayStruct)*nSize);
			pTemp = pObj;
			pTemp += nSize/2;
			memset(pTemp, 0, sizeof(SOAPArrayStruct)*nSize/2);
	}
	else
	{
		pObj = malloc(sizeof(SOAPArrayStruct));
		memset(pObj, 0, sizeof(SOAPArrayStruct));

		pTemp = pObj;
		pTemp->SOAPArrayStruct_varArray.m_Array = 0;
		pTemp->SOAPArrayStruct_varArray.m_Size = 0;
	}
	return pObj;
}
/**
 * This static method to deallocate a SOAPArrayStruct type of object
 */
void Axis_Delete_SOAPArrayStruct(SOAPArrayStruct* param, bool bArray, int nSize)
{
	int x;
	SOAPArrayStruct* pTemp;
	if (bArray)
	{
		/*delete any pointer members or array members of this struct here*/
		pTemp = param;
		for (x=0; x<nSize; x++)
		{
			if(pTemp->SOAPArrayStruct_varString) free(pTemp->SOAPArrayStruct_varString);
			if (pTemp->SOAPArrayStruct_varArray.m_Array) free(pTemp->SOAPArrayStruct_varArray.m_Array);
			pTemp++;
		}
		free(param);
	}
	else
	{
		/*delete any pointer members or array members of this struct here*/
		if(param->SOAPArrayStruct_varString) free(param->SOAPArrayStruct_varString);
		if (param->SOAPArrayStruct_varArray.m_Array) free(param->SOAPArrayStruct_varArray.m_Array);
		free(param);
	}
}
/**
 * This static method gives the size of SOAPArrayStruct type of object
 */
int Axis_GetSize_SOAPArrayStruct()
{
	return sizeof(SOAPArrayStruct);
}
