/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OutOfBoundStruct
 */

#if !defined(__OUTOFBOUNDSTRUCT_PARAM_H__INCLUDED_)
#define __OUTOFBOUNDSTRUCT_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>

#include "SpecialDetailStruct.h"

AXIS_CPP_NAMESPACE_USE

/*Local name and the URI for the type*/
static const char* Axis_URI_OutOfBoundStruct = "http://soapinterop.org/types";
static const char* Axis_TypeName_OutOfBoundStruct = "OutOfBoundStruct";

class SpecialDetailStruct;
class OutOfBoundStruct
{
public:
	xsd__string varString;
	int varInt;
	SpecialDetailStruct* specialDetail;
	OutOfBoundStruct();
	virtual ~OutOfBoundStruct();
};

#endif /* !defined(__OUTOFBOUNDSTRUCT_PARAM_H__INCLUDED_)*/
