/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub Class for remote web service 
 */

#if !defined(__INTEROPTESTPORTTYPEB_CLIENTSTUB_H__INCLUDED_)
#define __INTEROPTESTPORTTYPEB_CLIENTSTUB_H__INCLUDED_

#include <axis/client/Stub.hpp>
#include "AxisClientException.h"
#include <axis/ISoapFault.hpp>
#include "SOAPArrayStruct.h"
#include "SOAPStruct.h"
#include "SOAPStructStruct.h"

class InteropTestPortTypeB :public Stub
{
public:
	InteropTestPortTypeB(const char* pchEndpointUri, AXIS_PROTOCOL_TYPE eProtocol=APTHTTP);
	InteropTestPortTypeB();
public:
	virtual ~InteropTestPortTypeB();
public: 
	void echoStructAsSimpleTypes(SOAPStruct* Value0, AXIS_OUT_PARAM xsd__string *OutValue0, AXIS_OUT_PARAM int *OutValue1, AXIS_OUT_PARAM float *OutValue2);
	SOAPStruct* echoSimpleTypesAsStruct(xsd__string Value0,int Value1,float Value2);
	SOAPStructStruct* echoNestedStruct(SOAPStructStruct* Value0);
	SOAPArrayStruct* echoNestedArray(SOAPArrayStruct* Value0);
	int getFaultDetail(char** ppcDetail);
};

#endif /* !defined(__INTEROPTESTPORTTYPEB_CLIENTSTUB_H__INCLUDED_)*/
