///////////////////////////////////////////////////////////////////////////////////
//This file is automatically generated by the Axis C++ Wrapper Class Generator
//Web service wrapper class's implementation generated by Axis WCG
//Parameters and wrapper methos to manipulate SOAPStruct
////////////////////////////////////////////////////////////////////////////////////

#include "SOAPStruct.h"
#include <axis/common/AxisWrapperAPI.h>

/////////////////////////////////////////////////////////////////////////////
// This static method serialize a SOAPStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_Serialize_SOAPStruct(SOAPStruct* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->Serialize("<", Axis_TypeName_SOAPStruct, ">", NULL);
	}
	else
	{
		const AxisChar* sPrefix = pSZ->GetNamespacePrefix(Axis_URI_SOAPStruct);
		pSZ->Serialize("<", Axis_TypeName_SOAPStruct, " xsi:type=\"", sPrefix, ":",
			Axis_TypeName_SOAPStruct, "\" xmlns:", sPrefix, "=\"",
			Axis_URI_SOAPStruct, "\">", NULL);
	}

	pSZ->SerializeAsElement("varString", (void*)&(param->varString), XSD_STRING);
	pSZ->SerializeAsElement("varInt", (void*)&(param->varInt), XSD_INT);
	pSZ->SerializeAsElement("varFloat", (void*)&(param->varFloat), XSD_FLOAT);
	pSZ->Serialize("</", Axis_TypeName_SOAPStruct, ">", NULL);
	return AXIS_SUCCESS;
}

/////////////////////////////////////////////////////////////////////////////
// This static method deserialize a SOAPStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_DeSerialize_SOAPStruct(SOAPStruct* param, IWrapperSoapDeSerializer *pIWSDZ)
{
	param->varString = pIWSDZ->GetElementAsString(0,0);
	param->varInt = pIWSDZ->GetElementAsInt(0,0);
	param->varFloat = pIWSDZ->GetElementAsFloat(0,0);
	return AXIS_SUCCESS;
}
void* Axis_Create_SOAPStruct(void* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
		return new SOAPStruct[nSize];
	else
		return new SOAPStruct;
}

SOAPStruct::~SOAPStruct()
{
	free(varString);
}
/////////////////////////////////////////////////////////////////////////////
// This static method delete a SOAPStruct type of object
//////////////////////////////////////////////////////////////////////
void Axis_Delete_SOAPStruct(SOAPStruct* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/////////////////////////////////////////////////////////////////////////////
// This static method gives the size of SOAPStruct type of object
//////////////////////////////////////////////////////////////////////
int Axis_GetSize_SOAPStruct()
{
	return sizeof(SOAPStruct);
}
