/*
 *This file is automatically generated by the Axis C++ Wrapper Class Generator
 *Web service wrapper class's implementation generated by Axis WCG
 *Parameters and wrapper methos to manipulate SOAPStruct
 */

#include <malloc.h>
#include "SOAPStruct.h"
#include <axis/common/AxisWrapperAPI.h>

/**
 * This static method serialize a SOAPStruct type of object
 */
int Axis_Serialize_SOAPStruct(SOAPStruct* param, IWrapperSoapSerializer* pSZ, bool bArray)
{
	IWrapperSoapSerializerX* pSZX = pSZ->__vfptr;
	const AxisChar* sPrefix;
	if (bArray)
	{
		pSZX->Serialize(pSZ, "<", Axis_TypeName_SOAPStruct, ">", NULL);
	}
	else
	{
		sPrefix = pSZX->getNewNamespacePrefix(pSZ);
		pSZX->Serialize(pSZ, "<", Axis_TypeName_SOAPStruct, " xsi:type=\"", sPrefix, ":",
			Axis_TypeName_SOAPStruct, "\" xmlns:", sPrefix, "=\"",
			Axis_URI_SOAPStruct, "\">", NULL);
	}

	pSZX->Serialize(pSZ, pSZX->SerializeBasicType(pSZ, "varString", (void*)&(param->varString), XSD_STRING), NULL);
	pSZX->Serialize(pSZ, pSZX->SerializeBasicType(pSZ, "varInt", (void*)&(param->varInt), XSD_INT), NULL);
	pSZX->Serialize(pSZ, pSZX->SerializeBasicType(pSZ, "varFloat", (void*)&(param->varFloat), XSD_FLOAT), NULL);

	pSZX->Serialize(pSZ, "</", Axis_TypeName_SOAPStruct, ">", NULL);
	return AXIS_SUCCESS;
}

/**
 * This static method deserialize a SOAPStruct type of object
 */
int Axis_DeSerialize_SOAPStruct(SOAPStruct* param, IWrapperSoapDeSerializer *pDZ)
{
	IWrapperSoapDeSerializerX* pDZX = pDZ->__vfptr;
	param->varString = pDZX->GetString(pDZ);
	param->varInt = pDZX->GetInt(pDZ);
	param->varFloat = pDZX->GetFloat(pDZ);
	return AXIS_SUCCESS;
}
void* Axis_Create_SOAPStruct(bool bArray, int nSize)
{
	if (bArray && (nSize > 0))
		return malloc(sizeof(SOAPStruct)*nSize);
	else
		return malloc(sizeof(SOAPStruct));
}

/**
 * This static method delete a SOAPStruct type of object
 */
void Axis_Delete_SOAPStruct(SOAPStruct* param, bool bArray, int nSize)
{
	if (bArray)
	{
		free(param);
	}
	else
	{
		/*delete any pointer members or array members of this struct here*/
		free(param);
	}
}
/**
 * This static method gives the size of SOAPStruct type of object
 */
int Axis_GetSize_SOAPStruct()
{
	return sizeof(SOAPStruct);
}
