/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains definitions of the web service
 */

#include "NillableArrays.hpp"


NillableArrays::NillableArrays()
{
}

NillableArrays::~NillableArrays()
{
}

/* This function is called by the AxisEngine when something went wrong
 with the current web service request processing. Appropriate actions should
 be taken here.*/
void NillableArrays::onFault()
{
}

xsd__boolean_Array * NillableArrays::echoBooleanArray(xsd__boolean_Array * Value0)  
{
	return Value0;
}

xsd__short_Array * NillableArrays::echoShortArray(xsd__short_Array * Value0)  
{
	return Value0;
}

xsd__int_Array * NillableArrays::echoIntArray(xsd__int_Array * Value0)  
{
	return Value0;
}

xsd__long_Array * NillableArrays::echoLongArray(xsd__long_Array * Value0)  
{
	return Value0;
}

xsd__float_Array * NillableArrays::echoFloatArray(xsd__float_Array * Value0)  
{
	return Value0;
}

xsd__double_Array * NillableArrays::echoDoubleArray(xsd__double_Array * Value0)  
{
	return Value0;
}

xsd__string_Array * NillableArrays::echoStringArray(xsd__string_Array * Value0)  
{
	return Value0;
}
