/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains definitions of the web service
 */

#include "XSD_integer.hpp"


XSD_integer::XSD_integer()
{
}

XSD_integer::~XSD_integer()
{
}

/* This function is called by the AxisEngine when something went wrong
 with the current web service request processing. Appropriate actions should
 be taken here.*/
void XSD_integer::onFault()
{
}

xsd__integer XSD_integer::asNonNillableElement(xsd__integer Value0)  
{
	return Value0;
}
xsd__integer * XSD_integer::asNillableElement(xsd__integer * Value0)  
{
	return Value0;
}
RequiredAttributeElement* XSD_integer::asRequiredAttribute(RequiredAttributeElement* Value0)  
{
	return Value0;
}
OptionalAttributeElement* XSD_integer::asOptionalAttribute(OptionalAttributeElement* Value0)  
{
	return Value0;
}
xsd__integer_Array * XSD_integer::asArray(xsd__integer_Array * Value0)  
{
	return Value0;
}
SimpleComplexType* XSD_integer::asComplexType(SimpleComplexType* Value0)  
{
	return Value0;
}
