/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains definitions of the web service
 */

#include "XSD_short.hpp"


XSD_short::XSD_short()
{
}

XSD_short::~XSD_short()
{
}

/* This function is called by the AxisEngine when something went wrong
 with the current web service request processing. Appropriate actions should
 be taken here.*/
void XSD_short::onFault()
{
}

xsd__short XSD_short::asNonNillableElement(xsd__short Value0)  
{
	return Value0;
}
xsd__short * XSD_short::asNillableElement(xsd__short * Value0)  
{
	return Value0;
}
RequiredAttributeElement* XSD_short::asRequiredAttribute(RequiredAttributeElement* Value0)  
{
	return Value0;
}
OptionalAttributeElement* XSD_short::asOptionalAttribute(OptionalAttributeElement* Value0)  
{
	return Value0;
}
xsd__short_Array * XSD_short::asArray(xsd__short_Array * Value0)  
{
	return Value0;
}
SimpleComplexType* XSD_short::asComplexType(SimpleComplexType* Value0)  
{
	return Value0;
}
