/*
 *This file is automatically generated by the Axis C++ Wrapper Class Generator
 *Web service wrapper class's implementation generated by Axis WCG
 *Parameters and wrapper methos to manipulate SOAPStruct_Array
 */

#if !defined(__SOAPSTRUCT_ARRAY_ARRAY_H__OF_AXIS_INCLUDED_)
#define __SOAPSTRUCT_ARRAY_ARRAY_H__OF_AXIS_INCLUDED_

#include "SOAPStruct.h"

typedef struct SOAPStruct_ArrayTag
{
	SOAPStruct* m_Array;
	int m_Size;
} SOAPStruct_Array;

#endif /* !defined(__SOAPSTRUCT_ARRAY_ARRAY_H__OF_AXIS_INCLUDED_)*/
