///////////////////////////////////////////////////////////////////////////////////
//This file is automatically generated by the Axis C++ Wrapper Class Generator
//Web service wrapper class's implementation generated by Axis WCG
//Parameters and wrapper methos to manipulate ArrayOfString2D
////////////////////////////////////////////////////////////////////////////////////

#if !defined(__ARRAYOFSTRING2D_ARRAY_H__INCLUDED_)
#define __ARRAYOFSTRING2D_ARRAY_H__INCLUDED_

#include <axis/server/AxisUserAPI.h>

typedef struct ArrayOfString2DTag
{
	AxisChar** m_Array;
	int m_Size;
} ArrayOfString2D;

#endif // !defined(__ARRAYOFSTRING2D_ARRAY_H__INCLUDED_)
